Lỗi
System.Data.SqlClient.SqlException: 'The DELETE statement conflicted with the REFERENCE constraint "FK_tblKET_QUA_tblSINH_VIEN". The conflict occurred in database "Quanlydiem", table "dbo.tblKET_QUA", column 'MaSV'.
The statement has been terminated.'